// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAT_Proje.Models;

namespace SAT_Proje.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211214163904_sat")]
    partial class sat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SAT_Proje.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kullanıcı")
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("Şifre")
                        .HasColumnType("Varchar(10)");

                    b.HasKey("AdminID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("SAT_Proje.Models.Durum", b =>
                {
                    b.Property<int>("DurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MusterıSayısı")
                        .HasColumnType("int");

                    b.Property<int>("UrunSayısı")
                        .HasColumnType("int");

                    b.HasKey("DurumId");

                    b.ToTable("Durums");
                });

            modelBuilder.Entity("SAT_Proje.Models.Musterı", b =>
                {
                    b.Property<int>("MusterıId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MusterıAcıkAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusterıAdıSoyadı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusterıSehır")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musterıtel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SıparıDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("MusterıId");

                    b.HasIndex("UrunId");

                    b.ToTable("Musterı");
                });

            modelBuilder.Entity("SAT_Proje.Models.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UrunAcıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunAdet")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunBarkod")
                        .HasColumnType("int");

                    b.Property<int>("UrunFıyat")
                        .HasColumnType("int");

                    b.HasKey("UrunId");

                    b.ToTable("Uruns");
                });

            modelBuilder.Entity("SAT_Proje.Models.Musterı", b =>
                {
                    b.HasOne("SAT_Proje.Models.Urun", "urun")
                        .WithMany("Musterıs")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("urun");
                });

            modelBuilder.Entity("SAT_Proje.Models.Urun", b =>
                {
                    b.Navigation("Musterıs");
                });
#pragma warning restore 612, 618
        }
    }
}
